#!/bin/bash
# RLC Agent Installation Script
# Generated by RLC Setup Wizard

set -e

echo "Installing RLC Agents..."

# Create agents directory
mkdir -p .claude/agents/rlc

# Copy agents
cp agents/incident-commander.md .claude/agents/rlc/
cp agents/auto-remediator.md .claude/agents/rlc/
cp agents/post-mortem-writer.md .claude/agents/rlc/
cp agents/health-checker.md .claude/agents/rlc/
cp agents/metrics-collector.md .claude/agents/rlc/
cp agents/edge-function-monitor.md .claude/agents/rlc/
cp agents/deployment-monitor.md .claude/agents/rlc/
cp agents/threshold-evaluator.md .claude/agents/rlc/
cp agents/alert-router.md .claude/agents/rlc/
cp agents/auto-remediator.md .claude/agents/rlc/
cp agents/recovery-monitor.md .claude/agents/rlc/
cp agents/runbook-executor.md .claude/agents/rlc/

echo "✅ Agents installed"
echo ""
echo "Next steps:"
echo "  1. Review rlc-config.yaml"
echo "  2. Set up event handling per event-handling-setup.yaml"
echo "  3. Test with: python events/ingestion/event-ingester.py --help"
